server:
  port: 9988
spring:
  application:
    name: online-ordering-java
  profiles:
    active: prod

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 200MB # 文件上传大小限制
      max-request-size: 200MB # 请求大小限制

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  token-prefix: Bearer
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # 是否输出操作日志
  is-log: true
  jwt-secret-key: isaenterprisetemplateiknowsshoulebec
  is-read-cookie: false
  is-write-header: true

logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
  charset:
    console: utf-8

salt: $2a$10$s5vDkytJjx5rO.Zpm1stKe

server-config:
  ip: server-ip
  port: 22
  username: root
  password: root
  dir: /opt/files/

demo:
  mode: false # 演示模式